apiVersion: v1
kind: ConfigMap
metadata:
  name: bootnode-config
  namespace: default
data:
  bootnode-key: |
    698e055f1a486a22d69693fc79965f7bf47b4999eed073ef0acf305f703d6ec9

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-bootnode
  namespace: default
  labels:
    app: ethereum-bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-bootnode
  template:
    metadata:
      labels:
        app: ethereum-bootnode
    spec:
      containers:
        - name: bootnode
          image: ethereum/client-go:alltools-latest
          command: ["bootnode"]
          args: ["-nodekey", "/etc/bootnode/boot.key", "-addr", ":30310"]
          volumeMounts:
            - name: bootnode-key-volume
              mountPath: /etc/bootnode
              readOnly: true
      volumes:
        - name: bootnode-key-volume
          configMap:
            name: bootnode-config
            items:
              - key: bootnode-key
                path: boot.key

---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-bootnode-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 30310
      targetPort: 30310
      protocol: UDP
  selector:
    app: ethereum-bootnode
